AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for cloud file storage

Resources:
  StorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cloud-storage-demo-ankan
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Value: !Ref StorageBucket
